# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7739df479ac851e8f8885b87ce6625004ec38ae69e514b93f4b67bd43b7bf48c0082b41428242be1d3f5d6867b28106e56fee3753193c4fff749fe440d2baf3d

test:
  secret_key_base: 2ecbb6fa9b03459b215547c539cff15fb564c02e14cb89c3de77dd88f59c3e2df9b5aa2db6550a7ab4b29bf1f6a9505034be899ff95fef74591361d55ee5b109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
